# APPLICATION SCRIPTS

RUN set -eux; \
    composer dump-autoload --optimize --no-dev

RUN set -eux; \    
    mkdir -m777 -p dist/var && cp -r var/ dist/

    #cp app/config/parameters.example.yml app/config/parameters.yml; \


RUN echo 'pm.max_children = 70' >> /usr/local/etc/php-fpm.d/www.conf \
    && echo 'pm.start_servers = 10' >> /usr/local/etc/php-fpm.d/www.conf \
    && echo 'pm.min_spare_servers = 5' >> /usr/local/etc/php-fpm.d/www.conf \
    && echo 'pm.max_spare_servers = 20' >> /usr/local/etc/php-fpm.d/www.conf \
    && echo 'pm.max_requests = 500' >> /usr/local/etc/php-fpm.d/www.conf

RUN sed -i 's/memory_limit = .*/memory_limit = '768M'/' /usr/local/etc/php/conf.d/limits.ini


RUN  echo 'opcache.enable = 1' > /usr/local/etc/php/conf.d/21-cache.ini \
    && echo 'opcache.enable_cli = 1' >> /usr/local/etc/php/conf.d/21-cache.ini \
    && echo 'opcache.jit_buffer_size = 256M' >> /usr/local/etc/php/conf.d/21-cache.ini \
    && echo 'realpath_cache_size=4096K' >> /usr/local/etc/php/conf.d/21-cache.ini \
    && echo 'realpath_cache_ttl=3600' >> /usr/local/etc/php/conf.d/21-cache.ini \
    && echo 'opcache.validate_timestamps=0' >> /usr/local/etc/php/conf.d/21-cache.ini \
    && echo 'opcache.memory_consumption=256' >> /usr/local/etc/php/conf.d/21-cache.ini \
    && echo 'opcache.max_accelerated_files=20000' >> /usr/local/etc/php/conf.d/21-cache.ini \
    && chown www-data /usr/local/etc/php/conf.d/21-cache.ini 
