apiVersion: v1
kind: Service
metadata:
    name: gotenberg
    labels:
        app: gotenberg
    annotations:
spec:
    type: ClusterIP
    ports:
        - name: gotenberg
          protocol: TCP
          port: 3000
          targetPort: 3000
    selector:
        app: gotenberg
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gotenberg
    labels:
        app: gotenberg
spec:
    selector:
        matchLabels:
            app: gotenberg
    template:
        metadata:
            labels:
                app: gotenberg
        spec:
            containers:
                - name: gotenberg
                  image: gotenberg/gotenberg:7.10.1
                  resources:
                      limits:
                          cpu: 2000m
                          memory: 1024Mi
                      requests:
                          cpu: 200m
                          memory: 512Mi
                  env:
                      - name: DISABLE_GOOGLE_CHROME
                        value: "1"
                  ports:
                      - containerPort: 3000
                        protocol: TCP
                  livenessProbe:
                      tcpSocket:
                          port: 3000
                      initialDelaySeconds: 20
                      timeoutSeconds: 5
                      periodSeconds: 10
                      successThreshold: 1
                      failureThreshold: 2