apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
    component: "master"
  name: elasticsearch-discovery
spec:
  clusterIP: None
  ports:
    - port: 9300
      targetPort: transport
  selector:
    app: elasticsearch
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: elasticsearch
    component: "client"
  name: elasticsearch
spec:
  ports:
    - name: http
      port: 9200
      targetPort: http
  selector:
    app: elasticsearch
  type: ClusterIP
