apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: true
secretGenerator:
  - name: kk-registry-secret
    files:
      - .dockerconfigjson=docker.json
    type: kubernetes.io/dockerconfigjson
