apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pimcore-production
resources:
- config/
- php-fpm/
- services/
- ../secrets/
generatorOptions:
  # disableNameSuffixHash is true disables the default behavior of adding a
  # suffix to the names of generated resources that is a hash of
  # the resource contents.
  disableNameSuffixHash: true
