#!/bin/bash
set -e

# Note: we don't just use "apache2ctl" here because it itself is just a shell-script wrapper around apache2 which provides extra functionality like "apache2ctl start" for launching apache2 in the background.
# (also, when run as "apache2ctl <apache args>", it does not use "exec", which leaves an undesirable resident shell process)

if [[ ! -z "$FCGI_HOST" ]]; then
	echo "Replacing FCGI_HOST $FCGI_HOST"
	sed "s/php:/$FCGI_HOST:/" /etc/apache2/sites-available/000-default.conf >/tmp/virthost
	cp /tmp/virthost /etc/apache2/sites-available/000-default.conf

	echo "-----------"
	cat /etc/apache2/sites-available/000-default.conf
	echo "-----------"
	echo "sites-enabled:"
	ls -al /etc/apache2/sites-enabled
	echo "-----------"
	echo "sites-available:"
	ls -al /etc/apache2/sites-available
	echo "-----------"
	echo "apa2 dir"
	ls -al /etc/apache2
	echo "-----------"
	echo "APACHE_DOCUMENT_ROOT=$APACHE_DOCUMENT_ROOT"
	ls -al $APACHE_DOCUMENT_ROOT
	echo "-----------"
	echo "Apache conf"
	cat /etc/apache2/apache2.conf

	
fi

: "${APACHE_CONFDIR:=/etc/apache2}"
: "${APACHE_ENVVARS:=$APACHE_CONFDIR/envvars}"
if test -f "$APACHE_ENVVARS"; then
	. "$APACHE_ENVVARS"
fi

# Apache gets grumpy about PID files pre-existing
: "${APACHE_RUN_DIR:=/var/run/apache2}"
: "${APACHE_PID_FILE:=$APACHE_RUN_DIR/apache2.pid}"
rm -f "$APACHE_PID_FILE"

# create missing directories
# (especially APACHE_RUN_DIR, APACHE_LOCK_DIR, and APACHE_LOG_DIR)
for e in "${!APACHE_@}"; do
	if [[ "$e" == *_DIR ]] && [[ "${!e}" == /* ]]; then
		# handle "/var/lock" being a symlink to "/run/lock", but "/run/lock" not existing beforehand, so "/var/lock/something" fails to mkdir
		#   mkdir: cannot create directory '/var/lock': File exists
		dir="${!e}"
		while [ "$dir" != "$(dirname "$dir")" ]; do
			dir="$(dirname "$dir")"
			if [ -d "$dir" ]; then
				break
			fi
			absDir="$(readlink -f "$dir" 2>/dev/null || :)"
			if [ -n "$absDir" ]; then
				mkdir -p "$absDir"
			fi
		done

		mkdir -p "${!e}"
	fi
done

echo "Starting fpm status loop"
/fpm-status-loop.sh &

echo "Starting apache"
exec apache2 -DFOREGROUND "$@"