apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pimcore-website
  labels:
    app: pimcore-website
spec:
  endpoints:
    - port: metrics
      interval: 30s
  namespaceSelector:
    matchNames:
      - orthomol-dev
  selector:
    matchLabels:
      app: pimcore-website
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    app: pimcore-monitoring
  name: pimcore-monitoring-prometheus
  namespace: orthomol-dev
spec:
  groups:
  - name: Orthomol Apache
    rules:
    - alert: ApacheDown
      expr: apache_up == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: Apache down (instance {{ $labels.instance }})
        description: "Apache down\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: ApacheWorkersLoad
      expr: (sum by (instance) (apache_workers{state="busy"}) / sum by (instance) (apache_scoreboard) ) * 100 > 80
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Apache workers load (instance {{ $labels.instance }})
        description: "Apache workers in busy state approach the max workers count 80% workers busy on {{ $labels.instance }}\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
    - alert: ApacheRestart
      expr: apache_uptime_seconds_total / 60 < 1
      for: 0m
      labels:
        severity: warning
      annotations:
        summary: Apache restart (instance {{ $labels.instance }})
        description: "Apache has just been restarted.\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
