name: Deploy

on:
  workflow_dispatch:
    inputs:
      imagelabel:
        required: true
        description: 'Docker Image Label/Version (use numeric, never use "latest")'
        type: string
      environment:
        description: 'Environment'
        type: environment
        required: true
      pimcore_install:
        description: 'Run pimcore installation'
        required: false
        type: boolean

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}
  # Pre-set NAMESPACE_PREFIX from a GitHub variable if available
  NAMESPACE_PREFIX: ${{ vars.NAMESPACE_PREFIX }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - uses: kenchan0130/actions-system-info@master
        id: system-info

      - name: Cache kubectl
        id: cache-kubectl
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/kubectl
          key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-kubectl

      - name: Install kubectl
        run: |
          if [ -z "${{ steps.cache-kubectl.outputs.cache-hit }}" ]; then
            curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
            chmod +x ./kubectl
            sudo mv ./kubectl /usr/local/bin/kubectl
          else
            echo "Using cached kubectl"
          fi

      - name: Cache kubeval
        id: cache-kubeval
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/kubeval
          key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-kubeval

      - name: Install kubeval
        run: |
          if [ -z "${{ steps.cache-kubeval.outputs.cache-hit }}" ]; then
            curl -L https://github.com/instrumenta/kubeval/releases/latest/download/kubeval-linux-amd64.tar.gz -o kubeval.tar.gz
            tar xf kubeval.tar.gz
            chmod +x kubeval
            sudo mv kubeval /usr/local/bin
          else
            echo "Using cached kubeval"
          fi

      - id: lowercase-fully-qualified-image-name
        name: Lowercase fully qualified image name
        uses: ASzc/change-string-case-action@v2
        with:
          string: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Cache vendor directory
        id: cache-vendor
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-${{ steps.system-info.outputs.release }}-vendor-${{ hashFiles('**/composer.lock') }}

      - name: run devsetup composer install
        # if: steps.cache-vendor.outputs.cache-hit != 'true' # Skip if cache hit
        run: |
          ls -la
          test -d vendor && ls -la vendor/
          if [ -d vendor/krankikom ]; then
            echo "vendor/krankikom exists, skipping composer install"
          else
            ./devsetup-composer-install.sh
          fi

      - name: Set NAMESPACE_PREFIX if not already set
        run: |
          if [[ -z "${NAMESPACE_PREFIX}" ]]; then
            # NAMESPACE_PREFIX is not set, compute and set it
            PREFIX=$(echo "${GITHUB_REPOSITORY}" | cut -d '/' -f 2 | cut -d '-' -f 1)
            echo "Setting NAMESPACE_PREFIX to $PREFIX"
            echo "NAMESPACE_PREFIX=$PREFIX" >> "$GITHUB_ENV"
          else
            # NAMESPACE_PREFIX is already set, use the existing value
            echo "Using existing NAMESPACE_PREFIX: ${NAMESPACE_PREFIX}"
          fi

      - name: Generate KUBECONFIG
        run: |
          echo "Creating KUBECONFIG"
          export KUBECONFIG="$HOME/kubeconfig"
          touch $HOME/kubeconfig
          kubectl config set-cluster default --server=${KUBERNETES_URL}
          kubectl config set-credentials github-actions-sa --token=${KUBERNETES_TOKEN}
          kubectl config set-context default --user=github-actions-sa --cluster=default --namespace=${NAMESPACE}
          kubectl config use-context default
          echo "Testing KUBECONFIG"
          kubectl version || echo "ERROR: Somethings wrong with your VAR / Secret variables, env-secret KUBERNETES_TOKEN and repo-variable KUBERNETES_URL is set."
          echo "KUBECONFIG=$HOME/kubeconfig" >> "$GITHUB_ENV"
        env:
          KUBERNETES_TOKEN: ${{ secrets.KUBERNETES_TOKEN }}
          KUBERNETES_URL: ${{ vars.KUBERNETES_URL }}

      - name: Create docker config for ImagePullSecret
        run: |
          echo "Creating Docker Config"
          if [[ -d "./kubernetes/secrets" ]]; then
            if [[ -z "${GHCR_TOKEN}" ]]; then
              echo "ERROR: Secret 'GHCR_TOKEN' missing in Settings"
              exit 1
            fi
            export DOCKER_CONFIG="./kubernetes/secrets"
            echo $GHCR_TOKEN | docker login ghcr.io -u '$' --password-stdin
          fi
        env:
          GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}

      - name: Kustomize and kubectl apply
        run: |
          cd "kubernetes/$ENVIRONMENT"
          ls -al
          echo ""
          echo ""
          echo "---------------------------------"
          echo "Setting image version (php-fpm)"
          kustomize edit set image "${FULL_IMAGENAME_LOWER}:${IMAGELABEL}"
          echo "Setting image version (migrations)"
          kustomize edit set image "k-registry.krankikom.de/krankikom/pimcore-website=${FULL_IMAGENAME_LOWER}:${IMAGELABEL}"
          echo "Setting image version (apache)"
          kustomize edit set image "k-registry.krankikom.de/library/apache-fcgi=${FULL_IMAGENAME_LOWER}-apache:${IMAGELABEL}"
          cat kustomization.yaml
          echo "build dry-run"
          kustomize build
          echo "---------------------------------"
          echo "Running kubeval"
          kustomize build | kubeval --ignore-missing-schemas --strict --force-color
          echo "---------------------------------"
          echo "Deleting pimcore-migration Job (so we can recreate it) ... a failure is not a problem:"
          kubectl -n "${NAMESPACE_PREFIX}-${ENVIRONMENT}" delete job pimcore-migration || true
          echo "---------------------------------"
          echo "Running kubectl apply"
          kustomize build | kubectl apply -n "${NAMESPACE_PREFIX}-${ENVIRONMENT}" -f -
          echo "---------------------------------"
          echo "PIMCORE_INSTALL: $PIMCORE_INSTALL"
          if [ "$PIMCORE_INSTALL" != "false" ]; then
            echo "Running pimcore install"
            cd pimcore-install
            echo "Deleting pimcore-install Job (so we can recreate it) ... a failure is not a problem:"
            kubectl -n "${NAMESPACE_PREFIX}-${ENVIRONMENT}" delete job pimcore-install || true
            echo "Setting image version (php-fpm)"
            kustomize edit set image "k-registry.krankikom.de/krankikom/pimcore-website=${FULL_IMAGENAME_LOWER}:${IMAGELABEL}"
            echo "Setting namespace ${NAMESPACE_PREFIX}-${ENVIRONMENT}"
            kustomize edit set namespace "${NAMESPACE_PREFIX}-${ENVIRONMENT}"
            echo "build dry-run"
            kustomize build
            echo "Running kubeval"
            kustomize build | kubeval --ignore-missing-schemas --strict --force-color
            echo "Running kubectl apply"
            kustomize build | kubectl apply -n "${NAMESPACE_PREFIX}-${ENVIRONMENT}" -f -
            cd ..
          fi
        env:
          ENVIRONMENT: ${{ inputs.environment }}
          FULL_IMAGENAME_LOWER: ${{ steps.lowercase-fully-qualified-image-name.outputs.lowercase }}
          IMAGELABEL: ${{ inputs.imagelabel }}
          PIMCORE_INSTALL: ${{ inputs.pimcore_install }}
          KUBECFGSECRET: ${{ secrets.KUBECONFIG }}
          DOCKERJSON: ${{ secrets.DOCKERJSON }}
