services:
  php:
    environment:
        XDEBUG_MODE: debug
        XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    build:
        context: .
        dockerfile: Dockerfile.debug.compose
